<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Saya sudah membaca</name>
   <tag></tag>
   <elementGuidId>f15b4fd6-61a1-4e5a-8c13-21dd31cda5ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='setujuKebijakan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#setujuKebijakan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fed41577-2328-44bb-b087-99d36578a39a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5e2781e4-a6c3-4af4-b730-63b3f2e562ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>setujuKebijakan</value>
      <webElementGuid>5a4dfcfc-7540-42fc-a284-d8cdd6ee4ccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>setujuKebijakan</value>
      <webElementGuid>b1288da8-889a-4982-95c9-5f28e2a90a0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;setujuKebijakan&quot;)</value>
      <webElementGuid>e1aba46d-1fad-4c48-a1d6-10091730f904</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='setujuKebijakan']</value>
      <webElementGuid>1da2cacd-e01c-4899-95fa-e5aa6a2a7b82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='checkboxKebijakan']/input</value>
      <webElementGuid>7d882e07-1863-43da-926c-17836ec83478</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/input</value>
      <webElementGuid>8ce24757-8618-4d6b-aa2f-d50f1acaaba8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'setujuKebijakan' and @id = 'setujuKebijakan']</value>
      <webElementGuid>b2b8ed48-7acd-4aa4-8fd8-99a94b7a3648</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
