<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Saya tertarik update info terbaru</name>
   <tag></tag>
   <elementGuidId>21f590e9-0041-4818-a812-bde798698f23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='langganan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;langganan&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>956cf83c-3397-404a-91df-0e03ee69b499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a506df76-0d67-48a4-8e36-fbe342047da8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>langganan</value>
      <webElementGuid>cc27c61d-410d-4b5d-a76f-f39f235cd014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerFunderForm&quot;)/div[@class=&quot;wrapper-footer&quot;]/label[@class=&quot;text-light-check&quot;]/input[1]</value>
      <webElementGuid>75fa38b8-efd6-4584-b9d5-9a2fd0a84fd8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='langganan']</value>
      <webElementGuid>4ad673a7-732c-41eb-a8e5-374534a2fee9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerFunderForm']/div[2]/label/input</value>
      <webElementGuid>4542f18b-2767-4d59-bbb6-c774fbe3ce49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>4788c90b-1420-4645-81b6-23a7990db2df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'langganan']</value>
      <webElementGuid>d54aad43-6d58-48e0-aa3f-ae0e87a5aa21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
