<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Bismillahirrahmanirrahim</name>
   <tag></tag>
   <elementGuidId>404d37e4-2cf7-4b90-8305-619dacd01b07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='scrollWrapper']/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#scrollWrapper > p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>d1e2ea4e-dbcf-4fb9-a30f-cd7896e181a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bismillahirrahmanirrahim</value>
      <webElementGuid>ea5aaec6-a0f5-4106-b04b-643c055f0586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrollWrapper&quot;)/p[1]</value>
      <webElementGuid>119969f8-4426-4efd-bdc0-b2b72a165960</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scrollWrapper']/p</value>
      <webElementGuid>c4db5184-d447-4d05-a90a-d83bff1df90d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kebijakan Privasi &amp; Ketentuan Pengguna'])[1]/following::p[2]</value>
      <webElementGuid>7913582f-e70c-4492-976f-a66da4b6ded8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registrasi Pemberi Dana'])[1]/following::p[2]</value>
      <webElementGuid>6dc074f5-949a-4eca-9b9d-11c1e39ef0f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DEFINISI'])[1]/preceding::p[4]</value>
      <webElementGuid>032903e2-790a-4626-9ae9-6ae69a72aecf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ALAMI:'])[1]/preceding::p[4]</value>
      <webElementGuid>5767a10c-31bb-4c5d-a741-c2b942dfc407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bismillahirrahmanirrahim']/parent::*</value>
      <webElementGuid>8e3cfecb-6d60-4c7c-bd52-3e8565e41871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/p</value>
      <webElementGuid>0530c163-c921-4bbf-996c-f681e5e0494b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Bismillahirrahmanirrahim' or . = 'Bismillahirrahmanirrahim')]</value>
      <webElementGuid>6e38ede9-f43e-40d9-a553-9a50454db148</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
