<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Silahkan Pilih --</name>
   <tag></tag>
   <elementGuidId>594e196f-8105-4dec-b780-8e7f081abcd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='registerReferralId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#registerReferralId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>173d5134-1596-4eeb-af35-6e33fa97df36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registerReferralId</value>
      <webElementGuid>985f1353-af48-4d06-8497-d6019fb4b99b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>registerReferralId</value>
      <webElementGuid>9b59654d-26fa-4d13-80a7-ef922e2353fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3f1fa7ee-afda-435b-9a16-e8dccbdfb59c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    -- Silahkan Pilih --
                                    Facebook
                                    Instagram
                                    LinkedIn
                                    Lainnya
                                </value>
      <webElementGuid>3dc0745b-cabf-401c-adbc-eec8304fabe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerReferralId&quot;)</value>
      <webElementGuid>6ba38038-28ff-415e-bd6e-b70e3cb5b217</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='registerReferralId']</value>
      <webElementGuid>4519b5fb-859d-4513-8f39-3fd0b6f67406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerFunderForm']/div[7]/select</value>
      <webElementGuid>549749dd-a074-44e0-a99d-32740566f80a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bagaimana Kamu tahu ALAMI? (Opsional)'])[1]/following::select[1]</value>
      <webElementGuid>996eaf78-6d02-4092-aedf-45a26c9b3f7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kode Referral (Opsional)'])[1]/following::select[1]</value>
      <webElementGuid>f09c09d3-f246-494c-88f2-3bb680230868</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lanjutkan'])[1]/preceding::select[1]</value>
      <webElementGuid>6d37780b-547f-426e-86ef-67096031c886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar disini'])[1]/preceding::select[1]</value>
      <webElementGuid>8d0d7daf-c040-4dd4-b1b2-48c1be556dd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>65b98128-4759-4496-957e-8ce0948f69a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'registerReferralId' and @name = 'registerReferralId' and (text() = '
                                    -- Silahkan Pilih --
                                    Facebook
                                    Instagram
                                    LinkedIn
                                    Lainnya
                                ' or . = '
                                    -- Silahkan Pilih --
                                    Facebook
                                    Instagram
                                    LinkedIn
                                    Lainnya
                                ')]</value>
      <webElementGuid>d67934d5-f11b-4915-96b3-640ca4cdb1a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
