<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Klik Button Aktivasi</name>
   <tag></tag>
   <elementGuidId>10b244d1-2256-4df7-8460-d7e6e5645b81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ifmail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ifmail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>d16b2890-4c7c-4e55-a756-d118852f9860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>535ef696-5253-4f71-922d-2974cee61d09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>f7e2aafe-ae56-492d-9547-29eae76dec6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>6790be91-6211-410a-9c2e-1f154a97b181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ifmail</value>
      <webElementGuid>9030bd06-b316-479d-9201-1b1bbeb61b13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>onloadifmail()</value>
      <webElementGuid>7672a6db-1c27-41b5-a904-e46596dc6ccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ifmail</value>
      <webElementGuid>7957b4f3-7c9d-4d4c-96cf-28afa9cc35f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>state</name>
      <type>Main</type>
      <value>full</value>
      <webElementGuid>5bfbbfeb-3ffa-429f-80b4-1d5c24182cf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ifmail&quot;)</value>
      <webElementGuid>39fa74b2-bb6b-4075-93e9-97299b72719c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ifmail']</value>
      <webElementGuid>c7662c0b-627f-4851-811f-06e10b62eb2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wmmailmain']/iframe</value>
      <webElementGuid>5a67ea31-a5b7-4b53-afba-73d091ac47a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/iframe</value>
      <webElementGuid>4ec085f0-181a-4dea-985f-96a4583124e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'ifmail' and @id = 'ifmail']</value>
      <webElementGuid>f2b8d36a-1e79-40da-bab7-d4145ce48857</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
